package com.fip.mail_backup.controller;

import java.awt.event.ActionEvent;

    /**
     * @deprecated THIS INTERFACE IS DEPRECATED!    Never used.
     * => Buttons listener code has been automaticaly generated by the Swing GUI Builder in ProfileConfigView class
     */
@Deprecated
public interface ButtonsListener {

    void okPerformed(ActionEvent e);

    void cancelPerformed(ActionEvent e);

    void changeSrcPerformed(ActionEvent e);

    void changeTgtPerformed(ActionEvent e);
}
