/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.fip.mail_backup.view;

import com.fip.mail_backup.common.ProfileConfig;
import com.fip.mail_backup.controller.ProfileConfigController;
import com.fip.mail_backup.model.ListProfileConfigModel;
import javax.swing.JFrame;

/**
 * This frame manages editing/changing profile configuration (name and directory paths)
 * Presentation only. No user actions.
 * 
 * @author Fabien Ipseiz
 */
public class ProfileConfigView extends JFrame {

    private final int index;    
    private final ListProfileConfigModel model;
    private final ProfileConfig profile;
    
    /**
     * Creates new form ProfileConfigView
     * 
     * @param model
     * @param index
     */
    public ProfileConfigView(ListProfileConfigModel model, int index) {
        this.index = index;
        this.model = model;
        this.profile = model.getElementAt(index);
        
        // initialize the form
        initComponents();
        this.setNameText(profile.getProfileName());  
        this.setSrcText(profile.getSrc());
        this.setTgtText(profile.getTgt());
    }
    
    /**
     * Input the source directory with the selected directory path
     *
     * @param dirPath A selected directory path.
     */
    public final void setSrcText(String dirPath) {
        srcTextField.setText(dirPath);
    }

    /**
     * Input the target directory with the selected directory path
     *
     * @param dirPath A selected directory path.
     */
    public final void setTgtText(String dirPath) {
        tgtTextField.setText(dirPath);
    }

    /**
     * Input the profile name 
     *
     * @param name A selected profile name.
     */
    public final void setNameText(String name) {
        nameTextField.setText(name);
    }
    
    /**
     * @return the source directory text
     */
    public String getSrcText() {
        return srcTextField.getText();
    }

    /**
     * @return the target directory text
     */
    public String getTgtText() {
        return tgtTextField.getText();
    }

    /**
     * @return the target directory text
     */
    public String getNameText() {
        return nameTextField.getText();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contentPane = new javax.swing.JPanel();
        profileNamePanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        srcRowPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        srcTextField = new javax.swing.JTextField();
        changeSrcButton = new javax.swing.JButton();
        tgtRowPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        tgtTextField = new javax.swing.JTextField();
        changeTgtButton = new javax.swing.JButton();
        buttonsPanel = new javax.swing.JPanel();
        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Configure Profile");
        setResizable(false);

        contentPane.setName(""); // NOI18N

        profileNamePanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Profile name"));

        jLabel1.setText("Name:");

        javax.swing.GroupLayout profileNamePanelLayout = new javax.swing.GroupLayout(profileNamePanel);
        profileNamePanel.setLayout(profileNamePanelLayout);
        profileNamePanelLayout.setHorizontalGroup(
            profileNamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profileNamePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        profileNamePanelLayout.setVerticalGroup(
            profileNamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profileNamePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(profileNamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        srcRowPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Source directory"));
        srcRowPanel.setName(""); // NOI18N

        jLabel2.setText("Directory:");

        srcTextField.setToolTipText("");

        changeSrcButton.setActionCommand("change");
        changeSrcButton.setLabel("Change");
        changeSrcButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeSrcButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout srcRowPanelLayout = new javax.swing.GroupLayout(srcRowPanel);
        srcRowPanel.setLayout(srcRowPanelLayout);
        srcRowPanelLayout.setHorizontalGroup(
            srcRowPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(srcRowPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(srcTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(changeSrcButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        srcRowPanelLayout.setVerticalGroup(
            srcRowPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(srcRowPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(srcRowPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(srcTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(changeSrcButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tgtRowPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Target directory"));

        jLabel3.setText("Directory:");

        tgtTextField.setToolTipText("");

        changeTgtButton.setText("Change");
        changeTgtButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeTgtButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tgtRowPanelLayout = new javax.swing.GroupLayout(tgtRowPanel);
        tgtRowPanel.setLayout(tgtRowPanelLayout);
        tgtRowPanelLayout.setHorizontalGroup(
            tgtRowPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tgtRowPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tgtTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(changeTgtButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tgtRowPanelLayout.setVerticalGroup(
            tgtRowPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tgtRowPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tgtRowPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(changeTgtButton)
                    .addComponent(tgtTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        okButton.setText("OK");
        okButton.setMaximumSize(new java.awt.Dimension(65, 23));
        okButton.setMinimumSize(new java.awt.Dimension(65, 23));
        okButton.setPreferredSize(new java.awt.Dimension(65, 23));
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout buttonsPanelLayout = new javax.swing.GroupLayout(buttonsPanel);
        buttonsPanel.setLayout(buttonsPanelLayout);
        buttonsPanelLayout.setHorizontalGroup(
            buttonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonsPanelLayout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addComponent(okButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cancelButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        buttonsPanelLayout.setVerticalGroup(
            buttonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(okButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(cancelButton))
        );

        javax.swing.GroupLayout contentPaneLayout = new javax.swing.GroupLayout(contentPane);
        contentPane.setLayout(contentPaneLayout);
        contentPaneLayout.setHorizontalGroup(
            contentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(contentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tgtRowPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(srcRowPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(profileNamePanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        contentPaneLayout.setVerticalGroup(
            contentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentPaneLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(profileNamePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(srcRowPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tgtRowPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(contentPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(contentPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void changeSrcButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeSrcButtonActionPerformed
        ProfileConfigController profileController = new ProfileConfigController(index,model,this);
        profileController.changeSrcPerformed(evt);
    }//GEN-LAST:event_changeSrcButtonActionPerformed

    private void changeTgtButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeTgtButtonActionPerformed
        ProfileConfigController profileController = new ProfileConfigController(index,model,this);
        profileController.changeTgtPerformed(evt);
        
    }//GEN-LAST:event_changeTgtButtonActionPerformed

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        ProfileConfigController profileController = new ProfileConfigController(index,model,this);
        profileController.okPerformed(evt);
    }//GEN-LAST:event_okButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        ProfileConfigController profileController = new ProfileConfigController(index,model,this);
        profileController.cancelPerformed(evt);
    }//GEN-LAST:event_cancelButtonActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonsPanel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton changeSrcButton;
    private javax.swing.JButton changeTgtButton;
    private javax.swing.JPanel contentPane;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JButton okButton;
    private javax.swing.JPanel profileNamePanel;
    private javax.swing.JPanel srcRowPanel;
    private javax.swing.JTextField srcTextField;
    private javax.swing.JPanel tgtRowPanel;
    private javax.swing.JTextField tgtTextField;
    // End of variables declaration//GEN-END:variables

    void isAlwaysOnTop(boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
